fruits/Models/BasketItem.cs
namespace fruits.Models
{
	public class BasketItem
	{
        public int ProductId { get; set; }
        public int Count { get; set; }
    }
}

fruits/Models/HomePageProduct.cs
namespace fruits.Models
{
	public class HomePageProduct
	{
		public int Id { get; set; }
		public string ProductName { get; set; } = null!;
		public string ImagePath { get; set; } = null!;
		public decimal Price { get; set; }
	}
}

fruits/Models/News.cs
namespace fruits.Models

{
	public class News
	{
        public int Id { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        //public string ImagePath { get; set; }
    }
}

fruits/Models/Product.cs
namespace fruits.Models
{
	public class Product
	{
        public int Id { get; set; }
        public string ProductName { get; set; } = null!;
		public string ImagePath { get; set; } = null!;
		public decimal Price { get; set; }
    }
}

fruits/Models/Testimonial.cs
namespace fruits.Models

{
	public class Testimonial
	{
        public int Id { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Details { get; set; }
        public string ImagePath { get; set; }
    }
}

fruits/ViewModels/AboutIndexVM.cs
using fruits.Models;

namespace fruits.ViewModels
{
	public class AboutIndexVM
	{
		public List<Testimonial>Testimonials { get; set; }

	}
}

fruits/ViewModels/HomeIndexVM.cs
using fruits.Models;

namespace fruits.ViewModels
{
	public class HomeIndexVM
	{
		public List<HomePageProduct> Product { get; set; }
		public List<Testimonial>Testimonials { get; set; }

	}
}

fruits/ViewModels/NewsIndexVM.cs
using fruits.Models;

namespace fruits.ViewModels
{
	public class NewsIndexVM
	{
		public List<News> News { get; set; }

		
	}
}

fruits/ViewModels/ShopIndexVM.cs
using fruits.Models;

namespace fruits.ViewModels
{
	public class ShopIndexVM
	{
		public List <Product> Product { get; set; }

		
	}
}

fruits/Controllers/AboutController.cs
using fruits.Data;
using fruits.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace fruits.Controllers
{
	public class AboutController : Controller
	{
		public IActionResult Index()
		{

			var ViewModel = new AboutIndexVM
			{
				Testimonials = TestimonialRepository.GetTestimonials()

			};
			return View(ViewModel);
		}
	}
}

fruits/Controllers/HomeController.cs
using fruits.Data;
using fruits.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace fruits.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
			var ViewModel = new HomeIndexVM
			{
				Product =HomeProduct.GetProducts(),
				Testimonials=TestimonialRepository.GetTestimonials()
				
			};

			return View(ViewModel);

		}
		

	}
}

fruits/Controllers/NewsController.cs
using fruits.Data;
using fruits.ViewModels;
using Microsoft.AspNetCore.Mvc;
using fruits.Models;

namespace fruits.Controllers
{
	public class NewsController : Controller
	{

		List<News> _news;

		public NewsController()
		{
			_news = NewsRepository.GetNews();
		}

		public IActionResult Index()
		{
			NewsIndexVM model = new()
			{
				News = _news
			};

			return View(model);
		}

		public IActionResult SingleNews()
		{

			NewsIndexVM model = new()
			{
				News = _news
			};
			return View();
		}
	}
}

fruits/Views/Cart/Index.cshtml
@{
	ViewData["Title"] = "Cart";
}

<!-- search area -->
<div class="search-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<span class="close-btn"><i class="fas fa-window-close"></i></span>
				<div class="search-bar">
					<div class="search-bar-tablecell">
						<h3>Search For:</h3>
						<input type="text" placeholder="Keywords">
						<button type="submit">Search <i class="fas fa-search"></i></button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end search arewa -->
<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 offset-lg-2 text-center">
				<div class="breadcrumb-text">
					<p>Fresh and Organic</p>
					<h1>Cart</h1>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end breadcrumb section -->
<!-- cart -->
<div class="cart-section mt-150 mb-150">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-md-12">
				<div class="cart-table-wrap">
					<table class="cart-table">
						<thead class="cart-table-head">
							<tr class="table-head-row">
								<th class="product-remove"></th>
								<th class="product-image">Product Image</th>
								<th class="product-name">Name</th>
								<th class="product-price">Price</th>
								<th class="product-quantity">Quantity</th>
								<th class="product-total">Total</th>
							</tr>
						</thead>
						<tbody>
							<tr class="table-body-row">
								<td class="product-remove"><a href="#"><i class="far fa-window-close"></i></a></td>
								<td class="product-image"><img src="assets/img/products/product-img-1.jpg" alt=""></td>
								<td class="product-name">Strawberry</td>
								<td class="product-price">$85</td>
								<td class="product-quantity"><input type="number" placeholder="0"></td>
								<td class="product-total">1</td>
							</tr>
							<tr class="table-body-row">
								<td class="product-remove"><a href="#"><i class="far fa-window-close"></i></a></td>
								<td class="product-image"><img src="assets/img/products/product-img-2.jpg" alt=""></td>
								<td class="product-name">Berry</td>
								<td class="product-price">$70</td>
								<td class="product-quantity"><input type="number" placeholder="0"></td>
								<td class="product-total">1</td>
							</tr>
							<tr class="table-body-row">
								<td class="product-remove"><a href="#"><i class="far fa-window-close"></i></a></td>
								<td class="product-image"><img src="assets/img/products/product-img-3.jpg" alt=""></td>
								<td class="product-name">Lemon</td>
								<td class="product-price">$35</td>
								<td class="product-quantity"><input type="number" placeholder="0"></td>
								<td class="product-total">1</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>

			<div class="col-lg-4">
				<div class="total-section">
					<table class="total-table">
						<thead class="total-table-head">
							<tr class="table-total-row">
								<th>Total</th>
								<th>Price</th>
							</tr>
						</thead>
						<tbody>
							<tr class="total-data">
								<td><strong>Subtotal: </strong></td>
								<td>$500</td>
							</tr>
							<tr class="total-data">
								<td><strong>Shipping: </strong></td>
								<td>$45</td>
							</tr>
							<tr class="total-data">
								<td><strong>Total: </strong></td>
								<td>$545</td>
							</tr>
						</tbody>
					</table>
					<div class="cart-buttons">
						<a href="cart.html" class="boxed-btn">Update Cart</a>
					</div>
				</div>

				<div class="coupon-section">
					<h3>Apply Coupon</h3>
					<div class="coupon-form-wrap">
						<form action="index.html">
							<p><input type="text" placeholder="Coupon"></p>
							<p><input type="submit" value="Apply"></p>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end cart -->

fruits/Views/Home/Index.cshtml
@using fruits.Models;
@using fruits.ViewModels;

@model HomeIndexVM;

@{
    ViewData["Title"] = "Home";
}


<!-- search area -->
<div class="search-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<span class="close-btn"><i class="fas fa-window-close"></i></span>
				<div class="search-bar">
					<div class="search-bar-tablecell">
						<h3>Search For:</h3>
						<input type="text" placeholder="Keywords">
						<button type="submit">Search <i class="fas fa-search"></i></button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end search area -->
<!-- hero area -->
<div class="hero-area hero-bg">
	<div class="container">
		<div class="row">
			<div class="col-lg-9 offset-lg-2 text-center">
				<div class="hero-text">
					<div class="hero-text-tablecell">
						<p class="subtitle">Fresh & Organic</p>
						<h1>Delicious Seasonal Fruits</h1>
						<div class="hero-btns">
							<a href="shop.html" class="boxed-btn">Fruit Collection</a>
							<a href="contact.html" class="bordered-btn">Contact Us</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end hero area -->
<!-- features list section -->
<div class="list-section pt-80 pb-80">
	<div class="container">

		<div class="row">
			<div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
				<div class="list-box d-flex align-items-center">
					<div class="list-icon">
						<i class="fas fa-shipping-fast"></i>
					</div>
					<div class="content">
						<h3>Free Shipping</h3>
						<p>When order over $75</p>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
				<div class="list-box d-flex align-items-center">
					<div class="list-icon">
						<i class="fas fa-phone-volume"></i>
					</div>
					<div class="content">
						<h3>24/7 Support</h3>
						<p>Get support all day</p>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6">
				<div class="list-box d-flex justify-content-start align-items-center">
					<div class="list-icon">
						<i class="fas fa-sync"></i>
					</div>
					<div class="content">
						<h3>Refund</h3>
						<p>Get refund within 3 days!</p>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>
<!-- end features list section -->
<!-- product section -->
<div class="product-section mt-150 mb-150">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 offset-lg-2 text-center">
				<div class="section-title">
					<h3><span class="orange-text">Our</span> Products</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, fuga quas itaque eveniet beatae optio.</p>
				</div>
			</div>
		</div>

		<div class="row">
			@foreach(var product in Model.Product)
			{
				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-product-item">
						<div class="product-image">
							<a asp-controller="Shop" asp-action="SingleProduct"><img src="assets/img/products/@product.ImagePath" alt=""></a>
						</div>
						<h3>@product.ProductName</h3>
						<p class="product-price"><span>Per Kg</span> @product.Price </p>
						<a asp-controller="Cart" asp-action="Index" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
					</div>
				</div>
			}
			
		</div>
	</div>
</div>
<!-- end product section -->
<!-- cart banner section -->
<section class="cart-banner pt-100 pb-100">
	<div class="container">
		<div class="row clearfix">
			<!--Image Column-->
			<div class="image-column col-lg-6">
				<div class="image">
					<div class="price-box">
						<div class="inner-price">
							<span class="price">
								<strong>30%</strong> <br> off per kg
							</span>
						</div>
					</div>
					<img src="assets/img/a.jpg" alt="">
				</div>
			</div>
			<!--Content Column-->
			<div class="content-column col-lg-6">
				<h3><span class="orange-text">Deal</span> of the month</h3>
				<h4>Hikan Strwaberry</h4>
				<div class="text">Quisquam minus maiores repudiandae nobis, minima saepe id, fugit ullam similique! Beatae, minima quisquam molestias facere ea. Perspiciatis unde omnis iste natus error sit voluptatem accusant</div>
				<!--Countdown Timer-->
				<div class="time-counter"><div class="time-countdown clearfix" data-countdown="2020/2/01"><div class="counter-column"><div class="inner"><span class="count">00</span>Days</div></div> <div class="counter-column"><div class="inner"><span class="count">00</span>Hours</div></div>  <div class="counter-column"><div class="inner"><span class="count">00</span>Mins</div></div>  <div class="counter-column"><div class="inner"><span class="count">00</span>Secs</div></div></div></div>
				<a href="cart.html" class="cart-btn mt-3"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
			</div>
		</div>
	</div>
</section>
<!-- end cart banner section -->
<!-- testimonail-section -->
<div class="testimonail-section mt-150 mb-150">
	<div class="container">
		<div class="row">
			<div class="col-lg-10 offset-lg-1 text-center">
				<div class="testimonial-sliders">
					@foreach(var testimonial in Model.Testimonials)
					{
						<partial name="_TestimonialPartialView" model="testimonial" />
					}

				</div>
			</div>
		</div>
	</div>
</div>
<!-- end testimonail-section -->
<!-- advertisement section -->
<div class="abt-section mb-150">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-md-12">
				<div class="abt-bg">
					<a href="https://www.youtube.com/watch?v=DBLlFWYcIGQ" class="video-play-btn popup-youtube"><i class="fas fa-play"></i></a>
				</div>
			</div>
			<div class="col-lg-6 col-md-12">
				<div class="abt-text">
					<p class="top-sub">Since Year 1999</p>
					<h2>We are <span class="orange-text">Fruitkha</span></h2>
					<p>Etiam vulputate ut augue vel sodales. In sollicitudin neque et massa porttitor vestibulum ac vel nisi. Vestibulum placerat eget dolor sit amet posuere. In ut dolor aliquet, aliquet sapien sed, interdum velit. Nam eu molestie lorem.</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente facilis illo repellat veritatis minus, et labore minima mollitia qui ducimus.</p>
					<a asp-controller="About" asp-action="Index" class="boxed-btn mt-4">know more</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end advertisement section -->
<!-- shop banner -->
<section class="shop-banner">
	<div class="container">
		<h3>December sale is on! <br> with big <span class="orange-text">Discount...</span></h3>
		<div class="sale-percent"><span>Sale! <br> Upto</span>50% <span>off</span></div>
		<a asp-controller="Shop" asp-action="Index" class="cart-btn btn-lg">Shop Now</a>
	</div>
</section>
<!-- end shop banner -->
<!-- latest news -->
<div class="latest-news pt-150 pb-150">
	<div class="container">

		<div class="row">
			<div class="col-lg-8 offset-lg-2 text-center">
				<div class="section-title">
					<h3><span class="orange-text">Our</span> News</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, fuga quas itaque eveniet beatae optio.</p>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-4 col-md-6">
				<div class="single-latest-news">
					<a asp-controller="News" asp-action="SingleNews"><div class="latest-news-bg news-bg-1"></div></a>
					<div class="news-text-box">
						<h3><a asp-controller="News" asp-action="SingleNews">You will vainly look for fruit on it in autumn.</a></h3>
						<p class="blog-meta">
							<span class="author"><i class="fas fa-user"></i> Admin</span>
							<span class="date"><i class="fas fa-calendar"></i> 27 December, 2019</span>
						</p>
						<p class="excerpt">Vivamus lacus enim, pulvinar vel nulla sed, scelerisque rhoncus nisi. Praesent vitae mattis nunc, egestas viverra eros.</p>
						<a asp-controller="News" asp-action="SingleNews" class="read-more-btn">read more <i class="fas fa-angle-right"></i></a>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6">
				<div class="single-latest-news">
					<a asp-controller="News" asp-action="SingleNews"><div class="latest-news-bg news-bg-2"></div></a>
					<div class="news-text-box">
						<h3><a href="single-news.html">A man's worth has its season, like tomato.</a></h3>
						<p class="blog-meta">
							<span class="author"><i class="fas fa-user"></i> Admin</span>
							<span class="date"><i class="fas fa-calendar"></i> 27 December, 2019</span>
						</p>
						<p class="excerpt">Vivamus lacus enim, pulvinar vel nulla sed, scelerisque rhoncus nisi. Praesent vitae mattis nunc, egestas viverra eros.</p>
						<a asp-controller="News" asp-action="SingleNews" class="read-more-btn">read more <i class="fas fa-angle-right"></i></a>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 offset-md-3 offset-lg-0">
				<div class="single-latest-news">
					<a asp-controller="News" asp-action="SingleNews"><div class="latest-news-bg news-bg-3"></div></a>
					<div class="news-text-box">
						<h3><a asp-controller="News" asp-action="SingleNews">Good thoughts bear good fresh juicy fruit.</a></h3>
						<p class="blog-meta">
							<span class="author"><i class="fas fa-user"></i> Admin</span>
							<span class="date"><i class="fas fa-calendar"></i> 27 December, 2019</span>
						</p>
						<p class="excerpt">Vivamus lacus enim, pulvinar vel nulla sed, scelerisque rhoncus nisi. Praesent vitae mattis nunc, egestas viverra eros.</p>
						<a asp-controller ="News" asp-action="SingleNews" class="read-more-btn">read more <i class="fas fa-angle-right"></i></a>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12 text-center">
				<a asp-controller="News" asp-action="Index class="boxed-btn">More News</a>
			</div>
		</div>
	</div>
</div>
<!-- end latest news -->

fruits/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Fruitkha</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="~/assets/img/favicon.png">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="~/assets/css/all.min.css">
	<!-- bootstrap -->
	<link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
	<!-- owl carousel -->
	<link rel="stylesheet" href="~/assets/css/owl.carousel.css">
	<!-- magnific popup -->
	<link rel="stylesheet" href="~/assets/css/magnific-popup.css">
	<!-- animate css -->
	<link rel="stylesheet" href="~/assets/css/animate.css">
	<!-- mean menu css -->
	<link rel="stylesheet" href="~/assets/css/meanmenu.min.css">
	<!-- main style -->
	<link rel="stylesheet" href="~/assets/css/main.css">
	<!-- responsive -->
	<link rel="stylesheet" href="~/assets/css/responsive.css">

</head>
<body>

	<!--PreLoader-->
	<div class="loader">
		<div class="loader-inner">
			<div class="circle"></div>
		</div>
	</div>
	<!--PreLoader Ends-->
	<!-- header -->
	<div class="top-header-area" id="sticker">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="index.html">
								<img src="~/assets/img/logo.png" alt="">
							</a>
						</div>
						<!-- logo -->
						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li class="current-list-item">
									<a asp-controller="Home" asp-action="Index">Home</a>
									<ul class="sub-menu">
										<li><a asp-controller="Home" asp-action="Index">Static Home</a></li>
									</ul>
								</li>
								<li><a asp-controller="About" asp-action="Index">About</a></li>
								<li>
									<a asp-controller="News" asp-action="Index">News</a>
									<ul class="sub-menu">
										<li><a asp-controller="News" asp-action="Index">News</a></li>
										<li><a asp-controller="News" asp-action="SingleNews">Single News</a></li>

									</ul>
								</li>
								<li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
								<li>
									<a asp-controller="Shop" asp-action="Index">Shop</a>
									<ul class="sub-menu">
										<li><a asp-controller="Shop" asp-action="Index">Shop</a></li>
										<li><a asp-controller="Shop" asp-action="SingleProduct">Single Product</a></li>
										<li><a asp-controller="Cart" asp-action="Index">Cart</a></li>
									</ul>
								</li>
								<li>
									<div class="header-icons">
										<a class="shopping-cart" asp-controller="Cart" asp-action="Index"><i class="fas fa-shopping-cart"></i></a>
										<a class="mobile-hide search-bar-icon" href="#"><i class="fas fa-search"></i></a>
									</div>
								</li>
							</ul>
						</nav>
						<a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div>
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end header -->
            @RenderBody()
	<!-- logo carousel -->
	<div class="logo-carousel-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="logo-carousel-inner">
						<div class="single-logo-item">
							<img src="~/assets/img/company-logos/1.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="~/assets/img/company-logos/2.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="~/assets/img/company-logos/3.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="~/assets/img/company-logos/4.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="~/assets/img/company-logos/5.png" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end logo carousel -->
	<!-- footer -->
	<div class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="footer-box about-widget">
						<h2 class="widget-title">About us</h2>
						<p>Ut enim ad minim veniam perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box get-in-touch">
						<h2 class="widget-title">Get in Touch</h2>
						<ul>
							<li>34/8, East Hukupara, Gifirtok, Sadan.</li>
							<li>support@fruitkha.com</li>
							<li>+00 111 222 3333</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box subscribe">
						<h2 class="widget-title">Subscribe</h2>
						<p>Subscribe to our mailing list to get the latest updates.</p>
						<form action="index.html">
							<input type="email" placeholder="Email">
							<button type="submit"><i class="fas fa-paper-plane"></i></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end footer -->
	<!-- copyright -->
	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-12">
					<p>
						Copyrights &copy; 2019 - <a href="https://imransdesign.com/">Imran Hossain</a>,  All Rights Reserved.<br>
						Distributed By - <a href="https://themewagon.com/">Themewagon</a>
					</p>
				</div>
				<div class="col-lg-6 text-right col-md-12">
					<div class="social-icons">
						<ul>
							<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end copyright -->
	<!-- jquery -->
	<script src="~/assets/js/jquery-1.11.3.min.js"></script>
	<!-- bootstrap -->
	<script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
	<!-- count down -->
	<script src="~/assets/js/jquery.countdown.js"></script>
	<!-- isotope -->
	<script src="~/assets/js/jquery.isotope-3.0.6.min.js"></script>
	<!-- waypoints -->
	<script src="~/assets/js/waypoints.js"></script>
	<!-- owl carousel -->
	<script src="~/assets/js/owl.carousel.min.js"></script>
	<!-- magnific popup -->
	<script src="~/assets/js/jquery.magnific-popup.min.js"></script>
	<!-- mean menu -->
	<script src="~/assets/js/jquery.meanmenu.min.js"></script>
	<!-- sticker js -->
	<script src="~/assets/js/sticker.js"></script>
	<!-- main js -->
	<script src="~/assets/js/main.js"></script>

</body>
</html>

fruits/Views/Shared/_NewsPartialView.cshtml
@model fruits.Models.News;

<div class="col-lg-4 col-md-6">
	<div class="single-latest-news">
		<a asp-controller="News" asp-action="SingleNews"><div class="latest-news-bg news-bg-@Model.Id"></div></a>
		<div class="news-text-box">
			<h3><a asp-controller="News" asp-action="SingleNews">@Model.Title</a></h3>
			<p class="blog-meta">
				<span class="author"><i class="fas fa-user"></i> Admin</span>
				<span class="date"><i class="fas fa-calendar"></i> 27 December, 2018</span>
			</p>
			<p class="excerpt">@Model.Details</p>
			<a asp-controller="News" asp-action="SingleNews" class="read-more-btn">read more <i class="fas fa-angle-right"></i></a>
		</div>
	</div>
</div>

fruits/Views/Shared/_TestimonialPartialView.cshtml
@model fruits.Models.Testimonial;



<div class="single-testimonial-slider">
	<div class="client-avater">
		<img src="assets/img/avaters/@Model.ImagePath" alt="">
	</div>
	<div class="client-meta">
		<h3>@Model.Name <span>@Model.Position</span></h3>
		<p class="testimonial-body">
		@Model.Details
		</p>
		<div class="last-icon">
			<i class="fas fa-quote-right"></i>
		</div>
	</div>
</div>